# https://circleci.com/docs/2.0/language-go/
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    working_directory: /go/src/github.com/anyandrea/newsfeed

    steps:
    - checkout
    - run: go test -v ./.
    - deploy:
        name: appcloud push
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            chmod +x scripts/deploy.sh
            scripts/deploy.sh
          fi
